<!DOCTYPE html>
<html lang="en"><head>
<script src="08-slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="08-slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="08-slides_files/libs/quarto-html/popper.min.js"></script>
<script src="08-slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="08-slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="08-slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="08-slides_files/libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Gabriel Sotomayor">
  <meta name="dcterms.date" content="2025-10-13">
  <title>Descripción de Variables Categóricas</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="08-slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="08-slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="08-slides_files/libs/revealjs/dist/theme/quarto-aff1f7264a615286def6c13f54e8bcad.css">
  <link href="08-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="08-slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="08-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="08-slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <style>
  #title-slide .title {
    font-size: 2em;
  }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Descripción de Variables Categóricas</h1>
  <p class="subtitle">Unidad 4: Estadística Descriptiva Univariada</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Gabriel Sotomayor 
</div>
</div>
</div>

  <p class="date">2025-10-13</p>
</section>
<section id="objetivos-de-la-sesión-de-hoy" class="slide level2 smaller" data-background-color="white">
<h2>Objetivos de la Sesión de Hoy</h2>
<ul>
<li><strong>Revisar</strong> la distinción entre variables categóricas y cuantitativas.</li>
<li><strong>Calcular e interpretar</strong> tablas de frecuencias absolutas, relativas y porcentajes.</li>
<li><strong>Identificar</strong> la <strong>moda</strong> como la medida de tendencia central apropiada para datos categóricos.</li>
<li><strong>Comprender</strong> el concepto y la utilidad de las <strong>tasas</strong> en el análisis sociológico.</li>
<li><strong>Crear e interpretar</strong> gráficos de barras, discutiendo buenas prácticas de visualización.</li>
</ul>
</section>
<section>
<section id="el-primer-paso-del-análisis-describir" class="title-slide slide level1 center">
<h1>1. El Primer Paso del Análisis: Describir</h1>

</section>
<section id="repaso-y-conexión" class="slide level2 smaller" data-background-color="white">
<h2>Repaso y Conexión</h2>
<p>En la Unidad 3, aprendimos a <strong>preparar y manipular</strong> nuestras bases de datos en R. Ahora que tenemos los datos limpios y ordenados, comenzamos a <strong>analizarlos</strong>.</p>
<p>El primer paso de cualquier análisis de datos es la <strong>estadística descriptiva univariada</strong>: las herramientas que nos permitiran resumir y describir cada variable por sí sola.</p>
</section>
<section id="la-distinción-fundamental" class="slide level2 smaller" data-background-color="white">
<h2>La Distinción Fundamental</h2>
<p>Las herramientas que usamos para describir una variable dependen fundamentalmente de su tipo. Recordemos la distinción clave:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Variables Categóricas</strong></p>
<ul>
<li><strong>Definición:</strong> Indican a qué grupo o categoría pertenece una observación.<br>
</li>
<li><strong>Niveles de Medición:</strong> Nominal, Ordinal.<br>
</li>
<li><strong>Ejemplos:</strong> <code>sexo</code>, <code>region</code>, <code>nivel_educacional</code>.<br>
</li>
<li><strong>Análisis:</strong> Se basa en <strong>conteos</strong> de casos por categoría.<br>
</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Variables Cuantitativas (o Numéricas)</strong></p>
<ul>
<li><strong>Definición:</strong> Toman valores numéricos sobre los cuales las operaciones aritméticas tienen sentido.<br>
</li>
<li><strong>Niveles de Medición:</strong> Intervalo, Razón.<br>
</li>
<li><strong>Ejemplos:</strong> <code>edad</code>, <code>ingreso</code>, <code>años_escolaridad</code>.<br>
</li>
<li><strong>Análisis:</strong> Se basa en la descripción de la <strong>distribución</strong> de los valores.<br>
</li>
</ul>
</div></div>
<p><strong>Hoy, nos enfocaremos exclusivamente en las variables categóricas.</strong></p>
</section></section>
<section>
<section id="resúmenes-numéricos-para-variables-categóricas" class="title-slide slide level1 center">
<h1>2. Resúmenes Numéricos para Variables Categóricas</h1>

</section>
<section id="tablas-de-frecuencia-la-herramienta-central" class="slide level2 smaller" data-background-color="white">
<h2>Tablas de Frecuencia: La Herramienta Central</h2>
<p>La forma más básica y fundamental de describir una variable categórica es a través de una <strong>tabla de frecuencias</strong>. Esta tabla nos muestra la <strong>distribución</strong> de la variable: qué valores toma y con qué frecuencia.</p>
<ul>
<li><strong>Frecuencia Absoluta (<code>n</code>):</strong> Es el <strong>conteo simple</strong> del número de casos u observaciones en cada categoría.</li>
</ul>
<p><strong>Ejemplo: Distribución de la variable <code>sexo</code> en una muestra de 10 personas.</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Categoría (Sexo)</th>
<th style="text-align: center;">Frecuencia Absoluta (n)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Hombre</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">Mujer</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Total</strong></td>
<td style="text-align: center;"><strong>10</strong></td>
</tr>
</tbody>
</table>
<p>Nos dice <em>cuántos</em> hay en cada grupo, pero es difícil de comparar si los totales son diferentes.</p>
</section>
<section id="de-conteos-a-comparaciones-frecuencias-relativas" class="slide level2 smaller" data-background-color="white">
<h2>De Conteos a Comparaciones: Frecuencias Relativas</h2>
<div style="font-size: 0.9em; line-height: 1.2;">
<p>Para comparar la distribución de una variable entre grupos de diferentes tamaños, necesitamos estandarizar los conteos. Para esto usamos las <strong>frecuencias relativas</strong>.</p>
<ul>
<li><strong>Proporción:</strong> Es la frecuencia de una categoría dividida por el número total de casos. El valor va de 0 a 1.
<ul>
<li><em>Fórmula:</em> <code>Proporción = n_categoria / n_total</code></li>
</ul></li>
<li><strong>Porcentaje:</strong> Es la proporción multiplicada por 100. Es más fácil de interpretar y comunicar.
<ul>
<li><em>Fórmula:</em> <code>Porcentaje = (n_categoria / n_total) * 100</code></li>
</ul></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Categoría (Sexo)</th>
<th style="text-align: center;">Frecuencia (n)</th>
<th style="text-align: center;">Proporción</th>
<th style="text-align: center;">Porcentaje (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Hombre</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">40%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Mujer</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.6</td>
<td style="text-align: center;">60%</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Total</strong></td>
<td style="text-align: center;"><strong>10</strong></td>
<td style="text-align: center;"><strong>1.0</strong></td>
<td style="text-align: center;"><strong>100%</strong></td>
</tr>
</tbody>
</table>
<p>Ahora podemos decir que “el 60% de la muestra son mujeres”, una afirmación comparable con otras encuestas.</p>
</div>
</section>
<section id="la-moda-el-centro-de-las-categorías" class="slide level2 smaller" data-background-color="white">
<h2>La Moda: El Centro de las Categorías</h2>
<p>Para las variables categóricas, la única medida de tendencia central que podemos calcular es la <strong>moda</strong>.</p>
<ul>
<li><strong>Definición:</strong> La <strong>moda</strong> es la categoría que tiene la <strong>mayor frecuencia</strong> en una distribución.</li>
<li>Es la categoría “más típica” o “más común”.</li>
</ul>
<p><strong>Ejemplo: Afiliación religiosa en una muestra.</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Religión</th>
<th style="text-align: center;">Frecuencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Católica</td>
<td style="text-align: center;">450</td>
</tr>
<tr class="even">
<td style="text-align: left;">Evangélica</td>
<td style="text-align: center;">300</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ninguna</td>
<td style="text-align: center;">250</td>
</tr>
</tbody>
</table>
<p><strong>La moda es “Católica”</strong>, ya que es la categoría con el mayor número de casos (450).</p>
<p><em>Importante:</em> La moda es la <strong>categoría</strong> (“Católica”), no el número de casos (450).</p>
</section>
<section id="ejemplo-aplicado-la-fuerza-de-trabajo-en-chile" class="slide level2 smaller" data-background-color="white">
<h2>Ejemplo Aplicado: La Fuerza de Trabajo en Chile</h2>
<div style="font-size: 0.9em; line-height: 1.2;">
<p>Para aplicar estos conceptos, usaremos datos reales de la <strong>Encuesta Nacional de Empleo (ENE)</strong> del INE. Esta encuesta mide periódicamente el estado del mercado laboral en Chile y es fundamental para el diagnóstico y la creación de políticas públicas.</p>
<p>Nos centraremos en la variable <strong>condición de actividad (<code>activ</code>)</strong> para la población de 15 años y más. Esta variable categórica clasifica a las personas en tres grupos mutuamente excluyentes, que definen su relación con el trabajo remunerado:</p>
<ul>
<li><strong>Ocupados:</strong> Personas que trabajaron al menos una hora de forma remunerada durante la semana de referencia, o que, teniendo un empleo, no trabajaron temporalmente por razones específicas (vacaciones, enfermedad, etc.).</li>
<li><strong>Desocupados:</strong> Personas que no estaban ocupadas, pero que estaban disponibles para trabajar y habían realizado una búsqueda activa de empleo recientemente (cesantes y quienes buscan trabajo por primera vez).</li>
<li><strong>Inactivos o Fuera de la Fuerza de Trabajo:</strong> Personas que no estaban ocupadas ni buscaron activamente trabajo (ej. estudiantes, jubilados, personas dedicadas al trabajo doméstico no remunerado).</li>
</ul>
</div>
</section>
<section id="tabla-de-frecuencias-condición-de-actividad" class="slide level2 smaller" data-background-color="white">
<h2>Tabla de Frecuencias: Condición de Actividad</h2>
<p>El primer paso es construir una tabla de frecuencias para describir la distribución de esta variable. Usaremos los datos de la ENE para el trimestre móvil Junio-Julio-Agosto de 5.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<caption>Tabla 1: Distribución de la Condición de Actividad (Población 15 años y más)</caption>
<colgroup>
<col style="width: 39%">
<col style="width: 31%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">condicion_actividad</th>
<th style="text-align: right;">Frecuencia Absoluta (n)</th>
<th style="text-align: right;">Proporcion</th>
<th style="text-align: right;">Porcentaje</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ocupados/as</td>
<td style="text-align: right;">42467</td>
<td style="text-align: right;">0.431</td>
<td style="text-align: right;">43.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desocupados/as</td>
<td style="text-align: right;">3918</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fuera de la fuerza de trabajo</td>
<td style="text-align: right;">36286</td>
<td style="text-align: right;">0.368</td>
<td style="text-align: right;">36.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: right;">15929</td>
<td style="text-align: right;">0.162</td>
<td style="text-align: right;">16.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>Podemos observar que la categoría con la mayor frecuencia, es decir, la <strong>moda</strong>, es “Ocupado”.</li>
<li>El 53.1% de las personas encuestadas de 15 años y más se encontraba ocupada en este período, mientras que un 5% estaba desocupada y un 41.9% se encontraba fuera de la fuerza de trabajo.</li>
</ul>
</section>
<section id="de-la-muestra-a-la-población-un-problema-de-representatividad" class="slide level2 smaller" data-background-color="white">
<h2>De la Muestra a la Población: Un Problema de Representatividad</h2>
<div style="font-size: 0.9em; line-height: 1.2;">
<p>Hasta ahora, hemos contado los casos directamente de nuestra muestra (<code>n</code>). Sin embargo, si quisiéramos que nuestras conclusiones fueran representativas de todo Chile, <strong>usar las frecuencias absolutas o relativas directas sería un error.</strong></p>
<p><strong>El Problema:</strong> En una encuesta real y compleja como la ENE, no todas las personas tienen la misma probabilidad de ser seleccionadas y, además, no todas las personas seleccionadas aceptan responder.</p>
<p>Esto genera dos desafíos:</p>
<ol type="1">
<li><strong>Diseño Muestral Complejo:</strong> Personas en regiones rurales o menos pobladas pueden tener, por diseño, una mayor probabilidad de ser seleccionadas que alguien en Santiago.</li>
<li><strong>No Respuesta Diferencial:</strong> Ciertos grupos (ej. jóvenes, hombres, personas de mayores ingresos) tienden a responder menos a las encuestas.</li>
</ol>
<p>Si no corregimos esto, nuestra muestra no reflejará correctamente la estructura demográfica de Chile y nuestras estimaciones serán <strong>sesgadas</strong>.</p>
</div>
</section>
<section id="la-solución-ponderadores-o-factores-de-expansión" class="slide level2 smaller" data-background-color="white">
<h2>La Solución: Ponderadores o Factores de Expansión</h2>
<p>Para resolver este problema, los equipos estadísticos calculan una variable especial llamada <strong>ponderador</strong> o <strong>factor de expansión</strong>.</p>
<ul>
<li><strong>¿Qué es?</strong> Es un <strong>peso numérico</strong> que se le asigna a cada persona en la encuesta. Este peso indica <strong>a cuántas personas de la población total representa esa única persona entrevistada</strong>.</li>
<li><strong>¿Cómo se calcula?</strong> Es un proceso complejo que busca corregir varios problemas a la vez. El peso final de una persona se ajusta por:
<ul>
<li>Su probabilidad de selección original (diseño muestral).</li>
<li>La no respuesta de su grupo demográfico.</li>
<li>Otros ajustes (como <strong>cobertura</strong> del marco muestral y <strong>post-estratificación</strong>) para “calibrar” la muestra final con las proyecciones de población oficiales del INE (ej. por región, sexo y tramo de edad).</li>
</ul></li>
</ul>
</section>
<section id="ponderadores-en-la-práctica" class="slide level2 smaller" data-background-color="white">
<h2>Ponderadores en la Práctica</h2>
<div style="font-size: 0.9em; line-height: 1.2;">
<p>Al usar el ponderador, pasamos de describir la muestra a <strong>estimar las características de la población</strong>.</p>
<ul>
<li><strong>¿Cómo se usa?</strong> Al calcular cualquier estadística, en lugar de contar cada persona como “1”, la contamos según el valor de su ponderador.</li>
<li><strong>En R:</strong> En las bases de datos, esta variable suele llamarse <code>fact_cal</code> (en la ENE), <code>fexp</code>, <code>pond</code> o <code>weights</code>.</li>
<li><strong>Aplicación:</strong> Para calcular el conteo poblacional en nuestra tabla de frecuencias, usamos el argumento <code>wt</code> dentro de la función <code>count()</code>.</li>
</ul>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  condicion_actividad           Poblacion_Estimada Porcentaje
  &lt;fct&gt;                                      &lt;dbl&gt;      &lt;dbl&gt;
1 Ocupados/as                             9355097.      56.5 
2 Desocupados/as                           875888.       5.29
3 Fuera de la fuerza de trabajo           6312197.      38.2 </code></pre>
</div>
</div>
<p><strong>Nota sobre análisis avanzado:</strong> El análisis correcto de encuestas complejas (para calcular errores estándar, intervalos de confianza, etc.) requiere paquetes especializados como <code>survey</code>. Este es un tema avanzado, pero por ahora, es fundamental que sepan que <strong>para obtener estimaciones poblacionales, siempre deben usar el ponderador</strong>.</p>
</section>
<section id="tabla-ponderada-condición-de-actividad-en-la-población" class="slide level2 smaller" data-background-color="white">
<h2>Tabla Ponderada: Condición de Actividad en la Población</h2>
<p>Al aplicar el factor de expansión, nuestra tabla ya no describe la muestra, sino que <strong>estima la distribución para toda la población de 15 años y más en Chile</strong>. Estos porcentajes son los que coinciden con las cifras oficiales publicadas por el INE.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<caption>Tabla 2: Estimación de la Condición de Actividad (Población 15 años y más, ponderada)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Condición de Actividad</th>
<th style="text-align: right;">Población Estimada (n)</th>
<th style="text-align: right;">Porcentaje (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ocupados/as</td>
<td style="text-align: right;">9355097</td>
<td style="text-align: right;">56.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desocupados/as</td>
<td style="text-align: right;">875888</td>
<td style="text-align: right;">5.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fuera de la fuerza de trabajo</td>
<td style="text-align: right;">6312197</td>
<td style="text-align: right;">38.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Interpretación:</strong> Ahora podemos afirmar con propiedad que, para el trimestre Junio-Julio-Agosto de 2025, se estima que un 58.6% de la población de 15 años y más se encontraba ocupada, un 5.3% desocupada, y un 36.1% fuera de la fuerza de trabajo.</p>
</section>
<section id="tasas-una-medida-estandarizada-para-la-comparación" class="slide level2 smaller" data-background-color="white">
<h2>Tasas: Una Medida Estandarizada para la Comparación</h2>
<p>Una <strong>tasa</strong> es un tipo especial de frecuencia relativa que se usa para comparar la ocurrencia de un evento entre poblaciones de diferentes tamaños.</p>
<ul>
<li><strong>Definición:</strong> Relaciona el número de eventos de interés con el total de la población “en riesgo” de experimentar ese evento, multiplicado por una constante (generalmente 1.000, 10.000 o 100.000).</li>
<li><strong>Fórmula:</strong> <code>Tasa = (N° de eventos / Población total en riesgo) * k</code></li>
<li><strong>Uso Común:</strong> Tasas de natalidad, mortalidad, desempleo, homicidios, etc.</li>
</ul>
</section>
<section id="tasas-una-medida-estandarizada-para-la-comparación-1" class="slide level2 smaller" data-background-color="white">
<h2>Tasas: Una Medida Estandarizada para la Comparación</h2>
<p><strong>Ejemplo:</strong> Tasa de homicidios.</p>
<ul>
<li><strong>Comuna A:</strong> 10 homicidios en una población de 50.000.<br>
</li>
<li><strong>Comuna B:</strong> 20 homicidios en una población de 500.000.</li>
</ul>
<p>¿Dónde es más “violento”?</p>
<ul>
<li><strong>Tasa A:</strong> <code>(10 / 50.000) * 100.000 = 20</code> homicidios por cada 100.000 habitantes.<br>
</li>
<li><strong>Tasa B:</strong> <code>(20 / 500.000) * 100.000 = 4</code> homicidios por cada 100.000 habitantes.</li>
</ul>
<p><strong>Conclusión:</strong> Aunque la Comuna B tuvo más homicidios en términos absolutos, la Comuna A tiene una tasa de homicidios 5 veces mayor. Las tasas nos permiten hacer comparaciones justas.</p>
</section>
<section id="tasas-en-acción-analizando-la-crisis-de-natalidad-en-chile" class="slide level2 smaller" data-background-color="white">
<h2>Tasas en Acción: Analizando la Crisis de Natalidad en Chile</h2>
<p>Para ilustrar el poder de las tasas en el análisis sociológico, examinaremos uno de los cambios demográficos más profundos del Chile contemporáneo: la drástica caída de la natalidad. Para ello, usaremos dos indicadores clave.</p>
<ul>
<li><strong>Tasa Bruta de Natalidad:</strong>
<ul>
<li><em>¿Qué mide?</em> El número de nacidos vivos por cada 1.000 habitantes en un año determinado.</li>
<li><em>Utilidad:</em> Es una medida general de la frecuencia con que ocurren nacimientos en toda la población.</li>
</ul></li>
<li><strong>Tasa Global de Fecundidad (TGF):</strong>
<ul>
<li><em>¿Qué mide?</em> El número promedio de hijos/as que tendría una mujer al final de su vida fértil si mantuviera las tasas de fecundidad actuales.</li>
<li><em>Utilidad:</em> Es el indicador más preciso para medir el comportamiento reproductivo. Una TGF de <strong>2,1</strong> es considerada la “tasa de reemplazo” poblacional.</li>
</ul></li>
</ul>
</section>
<section id="la-caída-de-la-fecundidad-en-chile-1992-2024" class="slide level2 smaller" data-background-color="white">
<h2>La Caída de la Fecundidad en Chile (1992-2024)</h2>
<p>El siguiente gráfico visualiza la evolución de ambos indicadores. La línea roja punteada marca la tasa de reemplazo poblacional de 2,1 hijos por mujer.</p>

<img data-src="08-slides_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:90.0%"></section>
<section id="contexto-sociológico-por-qué-hay-menos-nacimientos" class="slide level2 smaller" data-background-color="white">
<h2>Contexto Sociológico: ¿Por qué hay menos nacimientos?</h2>
<p>La socióloga Martina Yopo, experta en género y reproducción, ofrece un diagnóstico complejo que va más allá de las decisiones individuales.</p>
<blockquote>
<p>“Mucha gente piensa que no hay futuro para hacer familia en Chile” — Martina Yopo</p>
</blockquote>
<p><strong>Algunas claves del fenómeno:</strong></p>
<ul>
<li><strong>Infertilidades Estructurales:</strong> No se trata solo de que las personas “no quieran” tener hijos, sino de la “falta de condiciones sociales para tener y criar hijos”.</li>
<li><strong>Tensiones Estructurales:</strong> Existe un conflicto entre el mundo del trabajo y la vida familiar, que recae desproporcionadamente sobre las mujeres. La maternidad a menudo obstaculiza el desarrollo laboral y personal.</li>
<li><strong>Futuro Incierto:</strong> La crisis climática, la inestabilidad política y la precariedad económica generan una “desesperanza estructural” que desincentiva la formación de familias.</li>
</ul>
</section></section>
<section>
<section id="visualización-de-variables-categóricas" class="title-slide slide level1 center">
<h1>3. Visualización de Variables Categóricas</h1>

</section>
<section id="gráfico-de-barras-la-herramienta-estándar" class="slide level2 smaller" data-background-color="white">
<h2>Gráfico de Barras: La Herramienta Estándar</h2>
<p>Las tablas de frecuencia son precisas, pero no siempre son la forma más rápida de comunicar un patrón. Nuestro cerebro procesa la información visual de manera mucho más eficiente.</p>
<p>El <strong>gráfico de barras</strong> es la forma más clara y efectiva de visualizar la distribución de una variable categórica.</p>
<ul>
<li>Cada barra representa una categoría.</li>
<li>La <strong>altura</strong> de la barra representa la frecuencia (absoluta o porcentual) de esa categoría.</li>
</ul>
</section>
<section id="gráfico-de-barras-nuestro-primer-vistazo-visual" class="slide level2 smaller" data-background-color="white">
<h2>Gráfico de Barras: Nuestro Primer Vistazo Visual</h2>

<img data-src="08-slides_files/figure-revealjs/bar-plot-basic-real-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p>Este gráfico es un buen primer paso. Nos permite ver de un vistazo que la categoría “Ocupado” es la moda. Sin embargo, el orden de las categorías es alfabético, lo que no es ideal para la comparación, y las frecuencias absolutas son difíciles de interpretar sin el total.</p>
</section>
<section id="buenas-prácticas-hacia-un-gráfico-informativo" class="slide level2 smaller" data-background-color="white">
<h2>Buenas Prácticas: Hacia un Gráfico Informativo</h2>
<p>Para que un gráfico de barras sea una herramienta de análisis poderosa y honesta, debe seguir algunas reglas:</p>
<ol type="1">
<li><strong>Usar Porcentajes:</strong> Son más fáciles de interpretar y comparar que las frecuencias absolutas.</li>
<li><strong>Ordenar las Barras:</strong> Ordenar las barras de mayor a menor (o viceversa) facilita la comparación visual y destaca la jerarquía.</li>
<li><strong>Etiquetar Directamente:</strong> Añadir los valores (porcentajes) directamente sobre las barras reduce la carga cognitiva del lector.</li>
<li><strong>Título y Subtítulo Informativos:</strong> El título debe comunicar el hallazgo principal, no solo describir el gráfico.</li>
<li><strong>Eje Y en Cero:</strong> Empezar el eje Y en un valor mayor a cero es una práctica engañosa que distorsiona las proporciones.</li>
</ol>
</section>
<section id="aplicando-buenas-prácticas-al-gráfico-de-la-ene" class="slide level2 smaller" data-background-color="white">
<h2>Aplicando Buenas Prácticas al Gráfico de la ENE</h2>
<p>Ahora, apliquemos todas estas reglas para crear un gráfico final de calidad de publicación.</p>

<img data-src="08-slides_files/figure-revealjs/bar-plot-improved-real-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="y-por-qué-no-un-gráfico-de-torta" class="slide level2 smaller" data-background-color="white">
<h2>¿Y por qué no un Gráfico de Torta?</h2>
<p>Aunque son muy populares, los gráficos de torta son desaconsejados por la mayoría de los expertos en visualización de datos.</p>

<img data-src="08-slides_files/figure-revealjs/pie-chart-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="y-por-qué-no-un-gráfico-de-torta-1" class="slide level2 smaller" data-background-color="white">
<h2>¿Y por qué no un Gráfico de Torta?</h2>
<p><strong>El Problema:</strong> Nuestro cerebro es muy malo para comparar <strong>ángulos</strong> y <strong>áreas</strong>, pero es muy bueno para comparar <strong>longitudes</strong> en una escala común (como las alturas de las barras).</p>
<p><strong>Pregunta:</strong> En el gráfico de torta, ¿es fácil ver qué tan grande es la categoría “Desocupado” en comparación con “Fuera de la fuerza de trabajo”? En el gráfico de barras, la comparación es instantánea.</p>
<p><strong>Regla General:</strong> Usa un gráfico de barras para comparar categorías. Reserva los gráficos de torta solo si tienes 2 o 3 categorías y quieres enfatizar la composición de un todo.</p>
</section>
<section id="cierre-y-próximos-pasos" class="slide level2 smaller" data-background-color="white">
<h2>Cierre y Próximos Pasos</h2>
<div style="font-size: 0.9em; line-height: 1.2;">
<p><strong>Resumen de la sesión de hoy:</strong></p>
<ul>
<li>Hemos aprendido que la descripción de <strong>variables categóricas</strong> se basa en el <strong>conteo</strong>.</li>
<li>Las <strong>tablas de frecuencia</strong> (absolutas y relativas) y la <strong>moda</strong> son nuestras herramientas numéricas fundamentales.</li>
<li>Las <strong>tasas</strong> nos permiten hacer comparaciones justas entre grupos de diferentes tamaños.</li>
<li>El <strong>gráfico de barras</strong> es la herramienta visual estándar y más efectiva para este tipo de variables.</li>
</ul>
<p><strong>En el práctico de hoy:</strong></p>
<ul>
<li>Aplicarán estas técnicas en R. Usarán <code>dplyr::count()</code> para crear tablas de frecuencia y <code>ggplot2::geom_bar()</code> para crear sus primeros gráficos de barras, poniendo en práctica las buenas prácticas de visualización.</li>
</ul>
<p><strong>Adelanto de la próxima clase:</strong></p>
<ul>
<li>Nos adentraremos en el mundo de las <strong>variables cuantitativas</strong>, aprendiendo a describir su forma, centro y dispersión con herramientas como el <strong>histograma</strong> y el <strong>boxplot</strong>.</li>
</ul>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="08-slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="08-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="08-slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="08-slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="08-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="08-slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="08-slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="08-slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="08-slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="08-slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>