<!DOCTYPE html>
<html lang="en"><head>
<script src="10-slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="10-slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="10-slides_files/libs/quarto-html/popper.min.js"></script>
<script src="10-slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="10-slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="10-slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="10-slides_files/libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Gabriel Sotomayor">
  <meta name="dcterms.date" content="2025-10-27">
  <title>La Media, la Desviación Estándar y la Estandarización</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="10-slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="10-slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="10-slides_files/libs/revealjs/dist/theme/quarto-e1cbb759e4a46ec0f203c77955f7056a.css">
  <link href="10-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="10-slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="10-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="10-slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="10-slides_files/libs/kePrint-0.0.1/kePrint.js"></script>

  <link href="10-slides_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <style>
  #title-slide .title {
    font-size: 2em;
  }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">La Media, la Desviación Estándar y la Estandarización</h1>
  <p class="subtitle">Unidad 4: Estadística Descriptiva Univariada</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Gabriel Sotomayor 
</div>
</div>
</div>

  <p class="date">2025-10-27</p>
</section>
<section id="objetivos-de-la-sesión-de-hoy" class="slide level2 smaller" data-background-color="white">
<h2>Objetivos de la Sesión de Hoy</h2>
<ul>
<li><strong>Calcular e interpretar</strong> la <strong>Media</strong> como medida de centro y entender su sensibilidad a valores atípicos.</li>
<li><strong>Utilizar</strong> la relación entre <strong>Media y Mediana</strong> como una herramienta de diagnóstico para la <strong>asimetría</strong>.</li>
<li><strong>Desglosar y comprender</strong> la <strong>Varianza</strong> y la <strong>Desviación Estándar</strong> como medidas de dispersión basadas en la media.</li>
<li><strong>Comprender</strong> el propósito y la aplicación de la estandarización a través de las <strong>Puntuaciones Z</strong>.</li>
</ul>
</section>
<section>
<section id="la-media-y-su-sensibilidad" class="title-slide slide level1 center">
<h1>1. La Media y su Sensibilidad</h1>

</section>
<section id="por-qué-necesitamos-la-media" class="slide level2 smaller" data-background-color="white">
<h2>¿Por qué Necesitamos la Media?</h2>
<p>En la clase anterior, vimos que la <strong>mediana</strong> es una excelente medida de centro, especialmente para distribuciones asimétricas, porque es <strong>robusta</strong>.</p>
<p><strong>Entonces, ¿por qué necesitamos otra medida de centro?</strong></p>
<p>La <strong>media (x̄)</strong>, o promedio aritmético, aunque es sensible a valores extremos, posee propiedades matemáticas que la convierten en la piedra angular de la estadística más avanzada (correlación, regresión, análisis de varianza).</p>
<p>La media representa el <strong>“centro de gravedad”</strong> de los datos: el punto de equilibrio de la distribución donde la suma de todas las desviaciones es cero.</p>
<p><span class="math display">\[
\bar{x} = \frac{\sum\_{i=1}^{n} x_i}{n}
\]</span></p>
</section>
<section id="la-sensibilidad-de-la-media-a-outliers" class="slide level2 smaller" data-background-color="white">
<h2>La Sensibilidad de la Media a Outliers</h2>
<p>La principal característica de la media es que <strong>utiliza el valor de cada observación</strong> en su cálculo. Esto la hace muy informativa, pero también <strong>no robusta</strong>.</p>
<p>Usemos un ejemplo de ingresos (en miles de $) para demostrarlo:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Grupo Original</strong></p>
<p><code>400, 450, 500, 550, 600</code></p>
<ul>
<li><strong>Mediana = 500</strong></li>
<li><strong>Media = (400+450+500+550+600) / 5 = 500</strong></li>
</ul>
<p>Aquí, la distribución es simétrica, y Media ≈ Mediana.</p>
</div><div class="column" style="width:50%;">
<p><strong>Grupo con Outlier</strong></p>
<p><code>400, 450, 500, 550, 15000</code></p>
<ul>
<li><strong>Mediana = 500</strong> (no cambia)</li>
<li><strong>Media = (400+450+500+550+15000) / 5 = 3380</strong></li>
</ul>
<p>El outlier “arrastra” la media hacia su valor.</p>
</div></div>
</section>
<section id="usando-la-media-y-la-mediana-para-diagnosticar-asimetría" class="slide level2 smaller" data-background-color="white">
<h2>Usando la Media y la Mediana para Diagnosticar Asimetría</h2>
<p>Esta diferencia en sensibilidad nos proporciona una poderosa <strong>herramienta de diagnóstico</strong> para complementar nuestros histogramas y boxplots.</p>

<img data-src="10-slides_files/figure-revealjs/unnamed-chunk-1-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="usando-la-media-y-la-mediana-para-diagnosticar-asimetría-1" class="slide level2 smaller" data-background-color="white">
<h2>Usando la Media y la Mediana para Diagnosticar Asimetría</h2>

<img data-src="10-slides_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="usando-la-media-y-la-mediana-para-diagnosticar-asimetría-ii" class="slide level2 smaller" data-background-color="white">
<h2>Usando la Media y la Mediana para Diagnosticar Asimetría (II)</h2>

<img data-src="10-slides_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p>La línea de la media es ligeramente superior a la de la mediana. Esto confirma visual y numéricamente que la distribución de la edad de los ocupados tiene una <strong>leve asimetría a la derecha</strong>, debido a la presencia de una “cola” de personas de mayor edad.</p>
</section></section>
<section>
<section id="medidas-de-dispersión-basadas-en-la-media" class="title-slide slide level1 center">
<h1>2. Medidas de Dispersión Basadas en la Media</h1>

</section>
<section id="hacia-una-medida-de-dispersión" class="slide level2 smaller" data-background-color="white">
<h2>Hacia una Medida de Dispersión</h2>
<p>Si la media es nuestro “centro de gravedad”, necesitamos una medida que nos diga qué tan lejos o cerca están los datos de este centro. La idea es encontrar la <strong>“distancia promedio”</strong> de cada observación a la media.</p>
<p><strong>Paso 1: Calcular las Desviaciones</strong></p>
<p>Para cada observación, calculamos su desviación (distancia) a la media: <code>(xᵢ - x̄)</code>.</p>

<img data-src="10-slides_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p><strong>Problema:</strong> Si sumamos todas las desviaciones, el resultado siempre será <strong>cero</strong>, porque la media es el punto de equilibrio. ¡No nos sirve para promediar!</p>
</section>
<section id="la-varianza-s²-promediando-las-distancias-al-cuadrado" class="slide level2 smaller" data-background-color="white">
<h2>La Varianza (s²): “Promediando” las Distancias al Cuadrado</h2>
<p>Para resolver el problema de los signos, elevamos cada desviación al cuadrado. Esto tiene dos ventajas:</p>
<ol type="1">
<li>Todos los valores se vuelven positivos.</li>
<li>Las desviaciones más grandes (outliers) son “penalizadas” con más fuerza, aportando más a la dispersión total.</li>
</ol>
<p>La <strong>Varianza (s²)</strong> es simplemente el “promedio” de estas desviaciones al cuadrado.</p>
<p><span class="math display">\[
s^2 = \frac{\sum\_{i=1}^{n} (x_i - \bar{x})^2}{n - 1}
\]</span></p>
<ul>
<li><strong>Interpretación:</strong> Es la “media de las desviaciones al cuadrado”.</li>
<li><strong>Desventaja:</strong> Sus unidades también están al cuadrado (ej. <code>pesos²</code>, <code>años²</code>), lo que la hace difícil de interpretar directamente.</li>
</ul>
</section>
<section id="la-desviación-estándar-s" class="slide level2 smaller" data-background-color="white">
<h2>La Desviación Estándar (s)</h2>
<p>Para volver a las unidades originales de la variable, simplemente sacamos la raíz cuadrada de la varianza.</p>
<p><span class="math display">\[
s = \sqrt{s^2} = \sqrt{\frac{\sum\_{i=1}^{n} (x_i - \bar{x})^2}{n - 1}}
\]</span></p>
<p>La <strong>Desviación Estándar (s)</strong> es la medida de dispersión más importante y utilizada.</p>
<ul>
<li><strong>Interpretación CLAVE:</strong> Es la <strong>“distancia típica” o “desviación promedio”</strong> de una observación respecto a la media.</li>
<li><strong>Ejemplo con Horas Trabajadas (ESI):</strong>
<ul>
<li>Media de horas efectivas: <strong>37.82 horas</strong>.</li>
<li>Varianza: <strong>249.43 horas²</strong>.</li>
<li>Desviación estándar: <strong>15.79 horas</strong>.</li>
<li><em>Interpretación:</em> Se estima que las personas ocupadas en Chile trabajan en promedio 37.8 horas a la semana, con una desviación típica de 15.8 horas.</li>
</ul></li>
</ul>
<p>Como la media, la desviación estándar es una medida <strong>no robusta</strong> y es sensible a los outliers.</p>
</section>
<section id="más-allá-del-centro-y-la-dispersión-la-forma-de-la-distribución" class="slide level2 smaller" data-background-color="white">
<h2>Más Allá del Centro y la Dispersión: La Forma de la Distribución</h2>
<p>Ya tenemos herramientas para medir el <strong>centro</strong> (media, mediana) y la <strong>dispersión</strong> (desviación estándar, IQR) de nuestros datos.</p>
<p>El último paso para una descripción completa es cuantificar la <strong>forma</strong> de la distribución. Mientras que un histograma nos da una idea visual, los estadísticos de forma nos dan un número preciso para describir dos características clave:</p>
<ol type="1">
<li><strong>Asimetría (Skewness):</strong> ¿La distribución es simétrica o está “cargada” hacia un lado?</li>
<li><strong>Curtosis (Kurtosis):</strong> ¿Qué tan “pesadas” son las colas de la distribución? ¿Es más propensa a generar valores extremos (outliers) que una distribución normal?</li>
</ol>
</section>
<section id="asimetría-skewness-midiendo-la-simetría" class="slide level2 smaller" data-background-color="white">
<h2>Asimetría (Skewness): Midiendo la Simetría</h2>
<p>La <strong>asimetría</strong> mide el grado en que los datos se distribuyen de forma no simétrica con respecto a su media. Confirma numéricamente lo que diagnosticamos al comparar la media y la mediana.</p>
<ul>
<li><strong>Interpretación del valor:</strong>
<ul>
<li><strong>Asimetría ≈ 0:</strong> Distribución <strong>simétrica</strong>.</li>
<li><strong>Asimetría &gt; 0 (Positiva):</strong> La cola derecha es más larga. La mayoría de los datos están a la izquierda.</li>
<li><strong>Asimetría &lt; 0 (Negativa):</strong> La cola izquierda es más larga. La mayoría de los datos están a la derecha.</li>
</ul></li>
</ul>
</section>
<section id="asimetría-skewness-midiendo-la-simetría-1" class="slide level2 smaller" data-background-color="white">
<h2>Asimetría (Skewness): Midiendo la Simetría</h2>

<img data-src="10-slides_files/figure-revealjs/unnamed-chunk-5-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="curtosis-kurtosis-midiendo-las-colas-y-los-outliers" class="slide level2 smaller" data-background-color="white">
<h2>Curtosis (Kurtosis): Midiendo las “Colas” y los Outliers</h2>
<p>La <strong>curtosis</strong> es una medida de qué tan “pesadas” son las colas de una distribución en comparación con una distribución normal. <strong>No mide si la distribución es “puntiaguda” o “plana”</strong>, sino su propensión a producir valores extremos.</p>
<ul>
<li><strong>Interpretación del valor (en exceso, respecto a la normal):</strong>
<ul>
<li><strong>Curtosis ≈ 0 (Mesocúrtica):</strong> Colas similares a una distribución normal.</li>
<li><strong>Curtosis &gt; 0 (Leptocúrtica):</strong> Colas “pesadas”. Hay más probabilidad de encontrar valores muy extremos (outliers).</li>
<li><strong>Curtosis &lt; 0 (Platicúrtica):</strong> Colas “ligeras”. Menos probabilidad de outliers que en una distribución normal.</li>
</ul></li>
</ul>
</section>
<section id="curtosis-kurtosis-midiendo-las-colas-y-los-outliers-1" class="slide level2 smaller" data-background-color="white">
<h2>Curtosis (Kurtosis): Midiendo las “Colas” y los Outliers</h2>

<img data-src="https://analystprep.com/cfa-level-1-exam/wp-content/uploads/2019/08/page-64.png" style="width:60.0%" class="r-stretch"></section>
<section id="estadísticos-de-forma-en-la-práctica" class="slide level2 smaller" data-background-color="white">
<h2>Estadísticos de Forma en la Práctica</h2>
<div style="font-size: 0.9em; line-height: 1.2;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped caption-top" data-quarto-postprocess="true" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Resumen de Estadísticos Descriptivos Ponderados (ESI 2024)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Desv. Estándar</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Asimetría</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Curtosis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Edad</td>
<td style="text-align: right;">43.03</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">13.27</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">-0.59</td>
</tr>
<tr class="even">
<td style="text-align: left;">Horas Trabajadas</td>
<td style="text-align: right;">37.82</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">15.79</td>
<td style="text-align: right;">-0.47</td>
<td style="text-align: right;">1.72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ingreso</td>
<td style="text-align: right;">897.018.71</td>
<td style="text-align: right;">611.000</td>
<td style="text-align: right;">1.043.897.45</td>
<td style="text-align: right;">14.98</td>
<td style="text-align: right;">702.66</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><strong>Edad:</strong> La Media (43.03) y Mediana (41) son cercanas, y la Asimetría (0.38) es positiva pero baja. La Curtosis (-0.59) es negativa. Esto confirma una distribución <strong>casi simétrica y platicúrtica</strong> (colas ligeras).<br>
</li>
<li><strong>Horas Trabajadas:</strong> La Media (37.82) es menor que la Mediana (44) y la Asimetría (-0.47) es negativa. La Curtosis (1.72) es positiva. Esto confirma una <strong>asimetría a la izquierda</strong> y una forma <strong>leptocúrtica</strong> (más propensa a outliers que una normal).<br>
</li>
<li><strong>Ingreso:</strong> La Media (897.019) es mucho mayor que la Mediana (611.000). La <strong>Asimetría es altísima (14.98)</strong>, confirmando una fuerte cola a la derecha. La <strong>Curtosis es extremadamente alta (702.66)</strong>, lo que indica que la distribución es muy propensa a generar valores atípicos (ingresos muy, muy altos).</li>
</ul>
</div>
</section></section>
<section id="estandarización-y-puntuaciones-z" class="title-slide slide level1 center">
<h1>3. Estandarización y Puntuaciones Z</h1>

</section>

<section>
<section id="estandarización-y-puntuaciones-z-1" class="title-slide slide level1 center">
<h1>3. Estandarización y Puntuaciones Z</h1>

</section>
<section id="comparando-entre-diferentes-variables" class="slide level2 smaller" data-background-color="white">
<h2>Comparando entre Diferentes Variables</h2>
<p>Imaginemos que queremos saber a quién le fue relativamente mejor en sus estudios. Tenemos dos estudiantes y sus notas en diferentes pruebas:</p>
<ul>
<li><strong>Estudiante A:</strong> Sacó un <strong>5.5</strong> en una prueba de Estadística.</li>
<li><em>(Población de la prueba de Estadística: Promedio = 4.0, Desviación Estándar = 0.5)</em></li>
<li><strong>Estudiante B:</strong> Sacó un <strong>6.2</strong> en una prueba de Metodología.</li>
<li><em>(Población de la prueba de Metodología: Promedio = 5.8, Desviación Estándar = 0.2)</em></li>
</ul>
<p>A primera vista, el 6.2 parece mejor que el 5.5. Pero, ¿considerando la dificultad y las notas de los demás, quién tuvo un rendimiento <em>relativamente</em> más destacado? No podemos comparar estas notas directamente porque provienen de pruebas con diferentes promedios y dispersiones. Necesitamos una escala común.</p>
</section>
<section id="la-puntuación-z-una-escala-universal" class="slide level2 smaller" data-background-color="white">
<h2>La Puntuación Z: Una Escala Universal</h2>
<p>La <strong>puntuación Z</strong> (o valor estandarizado) recalcula el valor de una observación para expresar su posición relativa a la media y a la dispersión de su grupo.</p>
<ul>
<li><p><strong>Fórmula:</strong> <span class="math display">\[
Z = \frac{\text{(Valor observado)} - \text{Media}}{\text{Desviación Estándar}} = \frac{x - \bar{x}}{s}
\]</span></p></li>
<li><p><strong>Interpretación Definitiva:</strong> Una puntuación Z nos dice <strong>cuántas desviaciones estándar por encima (+) o por debajo (-) de la media</strong> se encuentra una observación.</p></li>
<li><p><code>Z = 0</code>: La observación es exactamente igual a la media.</p></li>
<li><p><code>Z = +1</code>: La observación está una desviación estándar por encima de la media.</p></li>
<li><p><code>Z = -2</code>: La observación está dos desviaciones estándar por debajo de la media.</p></li>
</ul>
</section>
<section id="la-puntuación-z-una-escala-universal-1" class="slide level2" data-background-color="white">
<h2>La Puntuación Z: Una Escala Universal</h2>
<p>Estandarizar variables es fundamental porque permite llevar <strong>distintas variables a una escala común</strong> (con media 0 y desviación estándar 1). <strong>Esto es crucial en muchas técnicas estadísticas</strong> (como la regresión o el análisis factorial) donde las variables deben tener el mismo peso o ser directamente comparables, independientemente de sus unidades o rangos originales.</p>
</section>
<section id="resolviendo-el-problema-a-quién-le-fue-mejor-estudiante-a-o-b" class="slide level2 smaller" data-background-color="white">
<h2>Resolviendo el Problema: ¿A quién le fue mejor, Estudiante A o B?</h2>
<div style="font-size: 0.8em; line-height: 1.2;">
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Estudiante A (Prueba de Estadística)</strong></p>
<ul>
<li>Nota (x) = 5.5</li>
<li>Media (x̄) = 4.0</li>
<li>SD (s) = 0.5</li>
</ul>
<p><span class="math display">\[
Z\_{\text{A}} = \frac{5.5 - 4.0}{0.5} = \frac{1.5}{0.5} = +3.0
\]</span></p>
<p><strong>Interpretación:</strong> La nota del Estudiante A está <strong>3.0 desviaciones estándar por encima</strong> del promedio de su prueba. ¡Un rendimiento excepcional!</p>
</div><div class="column" style="width:50%;">
<p><strong>Estudiante B (Prueba de Metodología)</strong></p>
<ul>
<li>Nota (x) = 6.2</li>
<li>Media (x̄) = 5.8</li>
<li>SD (s) = 0.2</li>
</ul>
<p><span class="math display">\[
Z\_{\text{B}} = \frac{6.2 - 5.8}{0.2} = \frac{0.4}{0.2} = +2.0
\]</span></p>
<p><strong>Interpretación:</strong> La nota del Estudiante B está <strong>2.0 desviaciones estándar por encima</strong> del promedio de su prueba. También un muy buen rendimiento.</p>
</div></div>
<p><strong>Conclusión:</strong> Aunque el Estudiante B obtuvo una nota más alta en valor absoluto (6.2 vs 5.5), en términos <strong>relativos</strong> (es decir, en comparación con el desempeño del resto de sus compañeros en cada prueba), al <strong>Estudiante A le fue mejor</strong>. Su nota de 5.5 es mucho más atípica y superior respecto al promedio de su grupo que la nota de 6.2 del Estudiante B respecto al suyo.</p>
</div>
</section>
<section id="cierre-y-próximos-pasos" class="slide level2 smaller" data-background-color="white">
<h2>Cierre y Próximos Pasos</h2>
<p><strong>Resumen de la sesión de hoy:</strong></p>
<ul>
<li>La <strong>media</strong> es el “centro de gravedad” de los datos, pero es sensible a outliers.</li>
<li>La comparación <strong>Media vs.&nbsp;Mediana</strong> nos ayuda a diagnosticar la <strong>asimetría</strong>.</li>
<li>La <strong>desviación estándar</strong> es la “distancia típica” a la media y está en las unidades originales de la variable.</li>
<li>Las <strong>Puntuaciones Z</strong> nos permiten comparar valores de diferentes distribuciones al ponerlos en una escala universal.</li>
</ul>
<p><strong>En el práctico de hoy:</strong></p>
<ul>
<li>Aplicarán estas técnicas en R para calcular e interpretar <code>mean()</code>, <code>sd()</code> y puntuaciones Z con la Encuesta ESI.</li>
</ul>
<p><strong>Adelanto de la próxima clase:</strong></p>
<ul>
<li>Sintetizaremos todo lo aprendido en la Unidad 4, introduciendo la <strong>“Gramática de Gráficos”</strong> con <code>ggplot2</code> para construir visualizaciones de alta calidad de manera sistemática.</li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="10-slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="10-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="10-slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="10-slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="10-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="10-slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="10-slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="10-slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="10-slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="10-slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>