---
title: "Programa de Estudios: Descripción y Visualización de Datos"
author: "Facultad de Ciencias Sociales e Historia, Escuela de Sociología"
date: "2º semestre 2025"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
    latex_engine: xelatex
mainfont: "Garamond"
fontsize: 11pt
geometry: "left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm"
---

\newpage

# I. Identificación

-   **Código:** SOC09124
-   **Créditos:** 5
-   **Período Académico:** 2º semestre 2025
-   **Requisito:** SOC09114 MATEMÁTICAS PARA SOCIOLOGÍA
-   **Duración:** Semestral
-   **Horario de plenaria:** Lunes 08:30-9:50
-   **Horario de talleres:**
    -   Grupo 1: Lunes 10:00-11:20
    -   Grupo 2: Lunes 11:30-12:50
-   **Horario ayudantía:**
    -   Grupo 1: Lunes 14:30–15:50
    -   Grupo 2: Lunes 14:30–15:50
-   **Asistencia:** 70% (clases y ayudantías)
-   **Docente:** Gabriel Sotomayor López ([gabriel.sotomayor@mail.udp.cl](mailto:gabriel.sotomayor@mail.udp.cl))
-   **Ayudante:**
    -   Felipe Adasme ([felipe.adasme@mail.udp.cl](mailto:felipe.adasme@mail.udp.cl))
    -   Francisca Hernández ([francisca.hernandez_c@mail.udp.cl](mailto:francisca.hernandez_c@mail.udp.cl))
    -   Romina Zamorano ([romina.zamorano@mail.udp.cl](mailto:romina.zamorano@mail.udp.cl))

# II. Presentación

La estadística es una herramienta esencial para el quehacer sociológico moderno, ya que permite analizar diferentes dinámicas que se despliegan en todas las áreas de la vida social. Este curso busca entregar a los/las alumnos/as las herramientas básicas para establecer la relación entre la recolección de datos en investigaciones empíricas de carácter cuantitativo y las técnicas estadísticas apropiadas para el análisis, lectura e interpretación de los resultados. Para tales propósitos, el curso aborda elementos de la estadística descriptiva univariada como lo son la presentación de datos en tablas y gráficos, el cálculo e interpretación de estadígrafos de tendencia central, de dispersión, de forma y de posición; además de nociones básicas de estadística descriptiva bivariada y algunas reglas de asociación.

Los alumnos desarrollarán la capacidad de resumir información, analizarla y concluir sustantivamente respecto de cualquier problemática social que deban tratar. En consecuencia, el curso tiene un carácter eminentemente práctico a través de ejercicios y el uso de lenguajes de programación con orientación estadística que permitan el análisis y presentación adecuada de los datos. Finalmente, se busca que los/las alumnos/as comprendan el uso y la relevancia del análisis estadístico en las Ciencias Sociales y de forma particular en la Sociología.

# III. Resultados de Aprendizaje

## III.1. Resultado general

Aplicar los métodos y herramientas de la estadística descriptiva necesarios para el análisis de datos cuantitativos en las ciencias sociales.

## III.2. Resultados específicos:

-   Comprender el uso y relevancia de la estadística en las Ciencias Sociales.
-   Relacionar metodologías de recolección de datos y las técnicas estadísticas apropiadas para su análisis.
-   Comprender las principales herramientas de la estadística descriptiva.
-   Definir correctamente un plan de análisis descriptivo para una tabla de datos.
-   Identificar el estadístico apropiado según el tipo de variable analizada.
-   Manipular y analizar tablas de datos a través del lenguaje de programación R.
-   Interpretar datos cuantitativos producidos por investigaciones propias o de terceros.
-   Distinguir entre estadística descriptiva e inferencial.

Los puntos anteriores se realizarán utilizando el lenguaje de programación estadístico R junto a herramientas de apoyo como Word y Excel. Los/as estudiantes tendrán una base sólida en este lenguaje de programación.

# IV. Contenidos

## UNIDAD 1: Introducción a la estadística y su relación con las ciencias sociales

-   El proceso de conocimiento científico: lógica inductiva y deductiva.
-   Etapas generales de la investigación social empírica.
-   Datos: la fuente de información clave para la estadística.
-   La estadística como una aproximación a preguntas de investigación sociológicas.
-   Usos de la estadística en la actualidad: sociología, ciencia política, economía políticas públicas, otros.
-   La relevancia de los lenguajes de programación para el análisis estadístico actual.

## UNIDAD 2: Conceptos claves para la investigación social

-   Conceptualización y operacionalización.
-   Unidad de análisis vs unidad de observación.
-   Tipos de variables y niveles de medición.
-   Muestra y población: estadísticos muestrales y parámetros poblacionales.
-   Población objetivo, marco muestral, muestra.
-   Validez y confiabilidad en la medición.
-   Error de medición y error muestral.

## UNIDAD 3: Marcos de datos para la investigación social

-   Estructura de una tabla de datos: lógica filas, columnas.
-   Exploración de una tabla de datos en R.
-   Tipos de variables en una tabla de datos.
-   Introducción al `tidyverse`.
-   Manipulación de tablas de datos I: selecciones, filtros, ordenamiento.
-   Manipulación de tablas de datos II: uniones y pivot.
-   Recodificación de variables: uso de estructuras condicionales.
-   Construcción de variables: índices, escalas y tipologías.

## UNIDAD 4: Estadística Descriptiva Univariada

-   **Estadísticos para variables numéricas:**
    -   Estadísticos de centro: media, mediana, moda.
    -   Estadísticos de dispersión: rango, varianza, desviación estándar.
    -   Posición: percentiles.
    -   Forma: asimetría y curtosis.
-   **Estadístico para variables discretas o categóricas:**
    -   Frecuencias absolutas y relativas.
    -   Porcentajes.
    -   Tasas.
-   Visualización de datos descriptivas: barras, histogramas y boxplots.
-   Recomendaciones para la visualización de datos cuantitativos.

## UNIDAD 5: Estadística Descriptiva Bivariada

-   Tipos de asociaciones entre variables según su naturaleza.
-   Concepto de independencia.
-   Construcción de estadísticos por grupo.
-   Construcción de tablas de contingencia.
-   Control por tercera variable.
-   Visualizaciones bivariadas: barras, histogramas y boxplots.
-   Medidas de asociación: Pearson, spearman, gamma, policóricas.
-   Más allá de lo descriptivo: la probabilidad como medida de incertidumbre.

# V. Metodología

El curso se desarrollará en base a clases teóricas de modalidad expositivas y prácticas tipo taller. En ese sentido, durante las clases en aula se presentaran los contenidos del curso tanto a nivel teórico como práctico a través de ejemplos, además se realizarán guías de ejercicios grupales o individuales orientadas a la aplicación práctica de los contenidos. Algunas de las sesiones de clases serán destinadas al trabajo exclusivo en laboratorio de computación, en donde se abordará el trabajo con el lenguaje de programación R. Los contenidos del curso estarán disponibles en el sitio: <https://dyv25.netlify.app/>

Adicionalmente se realizará una sesión semanal de ayudantía con asistencia obligatoria a cargo de los ayudantes del curso, la que se realizará en el laboratorio de computación en un horario fijado con anterioridad. La ayudantía tendrá como objetivo entregar los elementos necesarios para el desarrollo y aplicación adecuada de los contenidos vistos en clases y la práctica de R como lenguaje de programación.

El ayudante, además de realizar las sesiones de ayudantía, tendrá la función de revisar los trabajos prácticos, en conjunto y bajo la supervisión del profesor. NO será labor del ayudante, a menos que esté dentro de la programación, hacer ayudantías especiales para los trabajos prácticos.

# VI. Evaluación

Se realizarán cuatro evaluaciones, todas de carácter obligatorio:

-   **Trabajo prácticos (TP: 30%)**
    Durante el semestre los/as estudiantes desarrollarán un total de 2 trabajos prácticos que evaluarán los contenidos del curso y los talleres. Estos trabajos se deberán realizar en grupo. En ellos se elaborarán los contenidos teóricos y prácticos abordados en las clases y ayudantías a partir de una pregunta de investigación propia. La pauta de cada trabajo práctico será entregada en clases o en ayudantía y los alumnos tendrán dos semanas para desarrollarlo. Para cada trabajo deberán entregar un informe en formato Word. El promedio simple de los 2 trabajos prácticos corresponderá al 30% de la nota de presentación a examen.

-   **Controles (CONT: 10%)**
    Durante las clases se aplicarán 5 controles individuales. Como regla general siempre habrá control al final de cada unidad (revise la programación). Las instrucciones se entregaran en la clase. En los controles se evaluaran los contenidos vistos en las clases anteriores, considerando la bibliografía del curso. El promedio simple de los 5 controles en clases corresponderá al 10% de la nota de presentación a examen. Se podrá borrar la peor nota.

-   **Tareas de R (TAR: 10%)**
    A lo largo del semestre ese realizarán 4 tareas de R individuales, en las cuales a partir de una pregunta de investigación y datos propuestos por el equipo docente los estudiantes deberán realizar un análisis de datos considerando las herramientas teóricas y prácticas desarrolladas en el curso.

-   **Pruebas solemnes (PS: 50%)**
    Tendremos dos pruebas solemnes que evaluarán conceptos, calculo, análisis e interpretación de datos. Los estudiantes deberán revisar las clases, talleres y bibliografía asignada. Cada prueba solemne equivale al 25% de la nota de presentación a examen.
    -   Primera prueba solemne: 06 de octubre 2025.
    -   Segunda prueba solemne: 01 de diciembre de 2025.
    -   Prueba recuperativa (ambas secciones): 08 de diciembre de 2025.

**Nota de presentación (NP: 70%)**
`NP = TP x 0,30 + CONT x 0,10 + TAR x 0,10 + PS x 0,50`

**Examen (30%)**
Habrá un examen donde se evaluará todos los contenidos del curso (clases, talleres, guías, ayudantías). Este examen equivale al 30% de la nota final del curso.
-   Examen para ambas secciones: fecha por confirmar

Se podrán eximir del examen aquellos estudiantes que tengan una nota de presentación igual a 5,5 siempre y cuando no tengan ninguna nota bajo 5,0 en las pruebas solemnes. La nota de presentación será la nota final del curso en ese caso. La nota mínima en el examen para aprobar el curso es un 3,5.

**Sobre los requisitos de aprobación:** se exigirá un 70% de asistencia como mínimo considerando clases y Ayudantías. El alumno/a que no cumpliere el requisito mínimo de asistencia, no tendrá derecho a rendir examen y reprobará el curso automáticamente. Se tomará en cada bloque. Si el estudiante se retira 15 minutos o más antes de finalizar la clase se considerará como ausente.

**Nota Final (NF)**
`NF = NP x 0,7 + Examen x 0,3`

Aquella persona que falta a una evaluación deberá rendir una prueba recuperativa que ponderará el % de la evaluación faltante. Quien falte a dos o más evaluaciones deberá rendir la prueba recuperativa y el examen. El porcentaje de las evaluaciones ausentes se sumará a la ponderación del examen.

# VII. Aspectos prácticos

## VII.1. Justificaciones y re-correcciones

Los/as estudiantes que, por razones médicas u otras, no entreguen alguna de estas evaluaciones del curso, deben seguir el procedimiento de justificación de evaluaciones definido por la unidad académica: “Si un estudiante falta a una evaluación, puede presentar ante la Secretaría de Estudios un certificado médico dentro de los cinco días hábiles posteriores a dicha evaluación, para tener derecho a rendir una prueba recuperativa. Las evaluaciones no rendidas tendrán nota 1.0. Los estudiantes tendrán derecho a un máximo de una prueba recuperativa por curso. Es decisión del profesor la fecha y modalidad en que se realizará dicha prueba”.

Según reglamento, los estudiantes tienen derecho a conocer las notas y la pauta de corrección de todas las evaluaciones en un plazo que no podrá exceder de 10 días hábiles contados desde la fecha desde que éstas fueran rendidas, como también a conocer el resultado de sus evaluaciones solemnes o principales, antes de rendir las siguientes de igual categoría en una misma asignatura.

Los estudiantes pueden imputar la corrección de cualquier evaluación escrita, en un plazo no superior a 5 días hábiles desde la entrega de la nota. Ello, a través de una carta dirigida profesor, que debe ir acompañada por la prueba, trabajo o informe evaluado y además, por las correcciones y comentarios que eventualmente haya entregado el/la docente. El académico deberá comunicar al estudiante el resultado de la recorrección, fundamentando por escrito sus argumentos, en un plazo no superior a los 5 días hábiles.

## VII.2. Ayudantías y tutorías

El ayudante tendrá un rol fundamental en el curso. Estará a cargo de realizar las ayudantias de R y resolver dudas respecto a los contenidos del curso. Además colaborará en la organización del curso, participará en las discusiones y estará a cargo de la corrección de las evaluaciones.

# VIII. Cronograma de trabajo

| Semana | Fecha | UNIDAD | Tópico | Evaluaciones | Lecturas Obligatorias / Ayudantía |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | **Clase:** Lunes, <br> 11-08-2025 | Unidad 1 | - Presentación del curso.<br>- El proceso de conocimiento científico.<br>- Etapas generales de la investigación social empírica.<br>- Datos: la fuente de información clave.<br>- La estadística como una aproximación a preguntas sociológicas. | | **Clase:**<br>- Babbie, E. (2000). Cap. 1. Pags. 4-26.<br>- Babbie, E. (2000). Cap. 2. Pags. 30-48.<br>- Cea D'Ancona M. (1996). Cap. 2. Pags. 81-120.<br>**Sin ayudantía** |
| 2 | **Clase:** Lunes, 18-08-2025 <br> **Ayudantía:** Lunes, 18-08-2025 | | - Usos de la estadística en la actualidad.<br>- La relevancia de los lenguajes de programación. | **Control N°1**<br>(en clases) | **Clase:**<br>- Moore, D. S. (2005). Razonamiento estadístico. Pags. 27-37.<br>**Ayudantía de R N°1 (parte 1)**<br>- Wickham, H., et al. (2023). Cap. 1, 3, 5, 7. |
| 3 | **Clase:** Lunes, 25-08-2025 <br> **Laboratorio:** Lunes, 25-08-2025 | Unidad 2 | - Conceptualización y operacionalización.<br>- Unidad de análisis vs unidad de observación.<br>- Tipos de variables y niveles de medición. | | **Clase:**<br>- Babbie, E. (2000). Cap. 5. Pags. 96-115.<br>- Babbie, E. (2000). Cap. 6. Pags. 117-138.<br>- Ritchey F. (2008). Cap. 2. Pags. 42-48.<br>- Asún, R. (2006). Medir la realidad social.<br>**Ayudantía de R N°1 (parte 2)**<br>- Wickham, H., et al. (2023). Cap. 3, 5.<br>- Urdinez, F., & Cruz, A. (2020). Cap. 1. R Básico. |
| 4 | **Clase:** Lunes, 01-09-2025 <br> **Laboratorio:** Lunes, 01-09-2025 | | - Muestra y población.<br>- Población objetivo, marco muestral.<br>- Validez y confiabilidad.<br>- Error de medición y error muestral. | **Control N°2**<br>(en clases)<br>**Tarea 1** | **Clase:**<br>- Babbie, E. (1996). Cap. 5. Pags. 147-175.<br>- Babbie, E. (2000). Cap. 4. Pags. 89-91.<br>- Babbie, E. (2000). Cap. 8. Pags. 176-191.<br>**Ayudantía de R N°2 (parte 1)** |
| 5 | **Clase:** Lunes, 08-09-2025 <br> **Laboratorio:** Lunes, 08-09-2025 | Unidad 3 | - Estructura de una tabla de datos.<br>- Exploración de una tabla de datos en R.<br>- Tipos de variables en una tabla de datos. | **Trabajo Práctico 1**<br>(3 semanas) | **Clase:**<br>- Babbie, E. (2000). Cap. 14. Pags. 336-342.<br>**Ayudantía de R N°2 (parte 2)**<br>- Wickham, H., et al. (2023). Cap. 8, 11. |
| | Lunes, 15-09-2025 | | **SEMANA DE RECESO POR FIESTAS PATRIAS** | | |
| 6 | **Clase:** Lunes, 22-09-2025 <br> **Ayudantía:** Lunes, 22-09-2025 | | - Manipulación de tablas de datos I y II. | | **Ayudantía de R N°3**<br>- Wickham, H., et al. (2023). Cap. 4, 6.<br>- Urdinez, F., & Cruz, A. (2020). Cap. 2. |
| 7 | **Clase:** Lunes, 29-09-2025 <br> **Ayudantía:** Lunes, 29-09-2025 | | - Recodificación y construcción de variables. | **Control N°3**<br>(en clases) | **Clase:**<br>- Babbie, E. (2000). Cap. 7. Pags. 144-167.<br>**Ayudantía: Preparación de la solemne I** |
| 8 | Lunes, 06-10-2025 | | **SOLEMNE 1 – CONTENIDO DE LA UNIDAD 1, 2 Y 3** | | |
| 9 | **Clase:** Lunes, 13-10-2025 <br> **Laboratorio:** Lunes | Unidad 4 | - Estadísticos de centro, dispersión y posición. | **Tarea 2** | **Clase:**<br>- Moore, D. S. (2005). Cap. 1. Pags. 32-54.<br>- Ritchey F. (2008). Cap. 4. Pags. 107-117.<br>- Ritchey F. (2008). Cap. 4. Pags. 136-154. |
| 10 | Lunes, 20-10-2025 | | - Forma: asimetría y curtosis.<br>- Frecuencias, porcentajes y tasas. | | **Clase:**<br>- Diez, D. M., et al. (2024). Cap. 2. Pags. 61-71.<br>- Ritchey F. (2008). Cap. 4. Pags. 52-61.<br>**Ayudantía de R N°4, N°5** |
| 11 | Lunes, 27-10-2025 | | - Visualización de datos y recomendaciones. | **Tarea 3** | **Clase:**<br>- Moore, D. S. (2005). Cap. 1. Pags. 3-24. |
| 12 | Lunes, 03-11-2025 | | - Introducción a la gramática de gráficos de ggplot2. | **Control N°4**<br>**Trabajo Práctico 2** | **Ayudantía de R N°6**<br>- Wickham, H., et al. (2023). Cap. 2. |
| 13 | Lunes, 10-11-2025 | Unidad 5 | - Tipos de asociaciones, independencia, estadísticos por grupo. | | **Clase:**<br>- Moore, D. S. (2005). Cap. 2. Pags. 98-128.<br>**Ayudantía de R N°7** |
| 14 | Lunes, 17-11-2025 | | - Construcción de tablas de contingencia y control. | **Tarea 4** | **Clase:**<br>- Moore, D. S. (2005). Cap. 2. Pags. 173-183.<br>**Ayudantía de R N°8** |
| 15 | Lunes, 24-11-2025 | | - Visualizaciones bivariadas: barras, histogramas, boxplots. | **Control N°5**<br>(en clases) | **Clase:**<br>- Ritchey F. (2008). Cap. 3. Pags. 78-94. |
| 16 | Lunes, 01-12-2025 | | **SOLEMNE II – CONTENIDO DE LA UNIDAD 4 Y 5** | | **Ayudantía: Preparación de la solemne II**<br>- Moore, D.S. (2005). Cap. 2, 4, 5.<br>- Urdinez, F., & Cruz, A. (2020). Cap. 3. |
| 17 | Lunes, 08-12-2025 | | **PRUEBA RECUPERATIVA** | | |
| | | | **EXAMEN: FECHA POR CONFIRMAR** | | |

*Nota: al final de cada semana se presentará la literatura obligatoria y complementaria.*

# IX. Bibliografía

## IX.1. Bibliografía Obligatoria

-   Asún, R. (2006). Medir la realidad social: El sentido de la metodología cuantitativa. En M. Canales, *Metodologías de investigación Social. Introducción a los oficios* (págs. 31- 62). Santiago: LOM.
-   Babbie, E. (1996) *Manual para la práctica de la investigación social*. Bilbao, España: Desclée De Brouwer.
-   Babbie, E. (2000). *Fundamentos de la investigación social*. Cengage Learning Latin Am.
-   Cea D’Ancona M. (1996) *Metodología Cuantitativa: Estrategias y Técnicas de Investigación Social*. Ed. Síntesis Sociológica, Madrid
-   Diez, D. M., Barr, C. D., & Çetinkaya-Rundel, M. (2024). *OpenIntro Statistics*. Creative Commons.
-   Hernández R., Fernández C. & Baptista P. (2010) *Metodología de la Investigación*. Mc Graw Hill
-   Moore, D. S. (2005). *Estadística aplicada básica*. Antoni Bosch editor.
-   Ritchey F. (2008) *Estadística para las ciencias sociales*. McGraw-Hill.
-   Urdinez, F., & Cruz, A. (2020). *R for political data science: a practical guide*. CRC Press. Disponible en: <https://arcruz0.github.io/libroadp/>
-   Wickham, H., Çetinkaya-Rundel, M., & Grolemund, G. (2023). *R for data science*. O'Reilly Media, Inc. Disponible en: <https://r4ds.hadley.nz/>

## IX.2. Bibliografía Complementaria

-   Çetinkaya-Rundel, M., & Hardin, J. (2021). *Introduction to Modern Statistics*. OpenIntro. Disponible en: <https://openintro-ims.netlify.app/>
-   Goldthorpe, J. H. (2017). *La sociología como ciencia de la población*. Madrid. Alianza Editorial.
-   Healey, J. F. (2015). *The essentials of statistics: A tool for social research*. Cengage Learning.

# X. Cláusula Ética y Normativas

## X.1. Cláusula Ética

La Escuela establece severas sanciones para las faltas graves que los estudiantes realicen, tales como plagio o falsificación de documentos, señalados en el Reglamento del Estudiante de Pre-grado en el Título XIII de las Conductas Contrarias a los Principios Universitarios.

El Comité de Ética es la instancia responsable de revisar y resolver las situaciones que sean contrarias a los principios universitarios, en relación al desarrollo de conductas ilícitas que vicien los procesos de evaluación. Son definidas como conductas que vician una evaluación, todos aquellos actos que implican un rompimiento de los estándares éticos que un estudiante debe resguardar en una evaluación, distorsionando la apreciación de los conocimientos y habilidades reales que el estudiante posee (por ejemplo, copia y uso indebido de documento y/o medios electrónicos, modificación o falsificación de documentos, plagio en trabajos escritos).

Se consideran como fuentes de información que se deben citar, los textos e imágenes en formato electrónico o en papel, en todas sus modalidades: libros, diarios, documentos de trabajo, artículos académicos, etc.

## X.2. Normativa sobre Prevención y Sanción de Acciones de Violencia Sexual UDP

### Párrafo I. De la violencia sexual

**Artículo 1.** Serán consideradas conductas de violencia sexual todos aquellos comportamientos, palabras o gestos de connotación sexual dirigidos hacia una persona (o personas) que sea integrante, beneficiario/a o contraparte de la Universidad, que no hayan sido consentidos por ella y que atenten contra su dignidad o integridad psicológica y/o física. Dada la realidad cultural y social previamente señalada, aun cuando en una gran mayoría de situaciones estas conductas de violencia sexual son realizadas por hombres hacia mujeres, esta normativa contempla e incluye toda violencia sexual cometida por una persona o grupo de personas contra otra persona o grupo de personas, independiente de su género.

**Artículo 2.** Se considerarán acciones de violencia sexual, sin que la enumeración sea taxativa, al acoso sexual, la agresión sexual, la exhibición, exposición y voyerismo sexual, el acecho sexual, verbalizaciones sexuales y, en general, cualquier interacción con significado sexual no consentido.

**Artículo 3.** Se denominará acoso u hostigamiento sexual a las insinuaciones y/o requerimientos de carácter sexual, no deseados, no consentidos, y que afecten la dignidad e integridad de quien los recibe. El acoso sexual ocurre cuando se sugiere explícita o implícitamente que la aceptación o el rechazo de dichas insinuaciones y/o requerimientos de carácter sexual tendrá incidencia en las condiciones laborales, académicas, personales y/o psicológicas de una persona o grupo de personas al interior de la Universidad, o bien cuando la conducta tiene el propósito o el efecto de interferir en la convivencia, salud mental, rendimiento académico o laboral de una persona o grupo de personas, creando un ambiente intimidante u hostil para quien o quienes afecta.

**Artículo 4.** Se considerará agresión sexual al acto o actos que se cometan mediante el uso de la fuerza, la amenaza del uso de la fuerza o cualquier otra forma de coacción, intimidación y/o amenaza física y/o verbal. En el marco de esta normativa, la agresión sexual incluye a la violación y el abuso sexual, sin perjuicio de la responsabilidad penal en que pueda incurrir su autor.

**Artículo 5.** La exhibición, exposición y el voyerismo sexual son conductas que buscan violar la privacidad de una persona en el ámbito de la sexualidad. Incluye conductas como presenciar u observar relaciones o actividades sexuales de otra(s) persona (s); desnudarse parcial o totalmente delante de terceras personas; grabar, fotografiar, y distribuir sin el consentimiento de la(s) persona(s) involucrada(s), por cualquier medio, imágenes de personas semidesnudas o desnudas, teniendo relaciones sexuales y/o desarrollando conductas sexuales.

**Artículo 6.** Son constitutivos de acecho sexual la acción o el conjunto de acciones con connotación sexual, dirigidas hacia una persona sin su consentimiento y que persiguen o tienen como efecto generar temor e inseguridad. Implica conductas como seguir, observar o vigilar a una persona, presentarse en su lugar de residencia, trabajo o estudio, llamar por teléfono, enviar mensajes, grabaciones, fotos, videos u objetos de connotación sexual, sin contar con el consentimiento de la persona que los recibe. Constituirá una agravante del acecho sexual el que la víctima de éste haya manifestado expresamente su rechazo hacia dicha acción o acciones, por cualquier medio.

**Artículo 7.** Las acciones de violencia sexual ocurren sin el consentimiento de las personas afectadas. El consentimiento se entiende como el acuerdo o aceptación de participar en una actividad sexual específica. Este se manifiesta de manera inequívoca mediante palabras o actos concluyentes de una persona que está en condiciones de consentir y se encuentra en pleno uso de sus facultades. Diversos factores impactan en cómo el consentimiento es dado y recibido, incluyendo las dinámicas de desigualdad de poder. Dado que el consentimiento no puede ser obtenido en circunstancias de amenaza, coerción de cualquier tipo o la fuerza, acuerdos obtenidos en estos contextos no constituyen consentimiento. El consentimiento para un acto sexual particular no puede interpretarse como consentimiento para actos sexuales posteriores. Asimismo, dentro de un mismo acto, inicialmente consentido, puede existir retractación. Del mismo modo, los actos sexuales previos o la existencia de una relación de pareja tampoco constituyen por sí misma expresión de consentimiento.

**Artículo 8.** El consumo de alcohol y/o de drogas podría reducir, e incluso eliminar la posibilidad de consentimiento. Considerando lo anterior, el hecho de encontrarse bajo la influencia del alcohol o de drogas, no exime de responsabilidad a quien incurre en conductas de violencia sexual, así como tampoco podrá presumirse la aceptación de la conducta por parte de la persona afectada por ésta.

### Párrafo II. De la violencia hacia las diversidades sexuales y de género

**Artículo 9.** Se entiende por violencia hacia la diversidad sexual y de género cualquier acción o conducta que atente contra la vida, integridad física o psíquica, o la libertad sexual de una persona y que se ejerce tomando en consideración el sexo, orientación sexual, identidad de género y/o la expresión de género de la persona. El concepto de violencia hacia la diversidad sexual y de género será entendido de manera amplia, abarcando de manera no taxativa conductas como las siguientes:
1.  Violencia física de tipo sexual, como tocamientos, golpes, heridas y/o empujones.
2.  Violencia psicológica, como humillaciones y/o amenazas.
3.  Violencia social, como inducir al aislamiento y alejamiento de redes de apoyo.
4.  Actos discriminatorios por identidad y/o expresión de género o por la orientación sexual de una persona.
5.  Difusión de información relativa a su sexualidad y/o género.
6.  No respetar el nombre social de una persona, cuando ha sido solicitado su uso.

**Artículo 10.** Cualquier persona podrá presentar una denuncia cuando haya presenciado directamente actos o conductas discriminatorias en atención al género o contra la diversidad sexual. En este caso, la persona denunciante, aunque no sea víctima directa, deberá llevar adelante la denuncia de conformidad a lo establecido en los artículos 26 y siguientes de esta normativa.

**Artículo 11.** Si la violencia hacia la diversidad sexual y de género se da en conjunto con algún tipo de violencia sexual, se considerará como una agravante. Sin embargo, la violencia hacia la diversidad sexual y de género es sancionable por sí sola, con independencia de si se realizó en conjunto con un acto de violencia sexual.

**Artículo 12.** No es necesario que exista violencia sistemática, o actos reiterados de violencia para recurrir a esta normativa. Una sola acción puede constituir un acto de violencia.

**Más información:** <https://genero.udp.cl/por-una-cultura-libre-de-discriminacion-y-violencia-2-2/normativa-de-prevencion-y-sancion-de-acciones-de-discriminacion-violencia-sexual-y-o-de-genero/>

## X.3. Uso de Inteligencia Artificial (IA)

El uso de cualquier tipo de herramientas de inteligencia artificial (IA) en este curso debe contar con la autorización explícita del profesor, ya que su utilización tiene que estar en sintonía con los objetivos de aprendizaje y el tipo de evaluaciones que se han definido en el presente programa de curso. Esto puede significar que ninguna o que algunas de las actividades permiten el uso de IA.

Su uso sin autorización puede afectar el aprendizaje de habilidades claves de la asignatura y, además, constituir una falta ética, de acuerdo con lo establecido en el Reglamento de Facultad.

Es importante realizar la consulta al profesor responsable si existen dudas sobre el uso de una herramienta de IA en una tarea o una evaluación.

<p>Puedes descargar el programa apretando el siguiente botón:
<a Puedes descargar el programa apretando el siguiente botón class="btn btn-primary" href="../files/Descripción y Visualización de Datos UDP 2º semestre 2025.pdf/" role="button"><i class="far fa-file-pdf"></i></a></p>